### ISSUE TITLE
Is iOS 16 support possible?

### ISSUE THREAD

**Issue by liunice** [christianselig/TinyStorage#5]
My app has to support iOS 16...

I noticed you delcare TinyStorage as @Observable, how about using ObservableObject?

**Comment by liunice** [comment]
@christianselig okay I got it, thanks for your hard work!

**Comment by newky2k** [comment]
@liunice I have created a fork of this project and removed the @observable flag and reduced the minimum iOS to 14 and updated it to use version of 5.7 of the swift-tools.   I don't currently need the observation features, but this could be added back via ObservableObject in the future.

I'll try and keep the changes in sync with the main project, where possible.

https://github.com/newky2k/TinyStorage

**Comment by liunice** [comment]
@newky2k This is so good! Thanks for your effort!

**Comment by christianselig** [comment]
Thanks @newky2k, I'll add that to the main README!
